version: '3.8'
services:
  batlight:
    container_name: batlight
    image: batuatalay/batlight
    ports:
      - "80:3000"
      - "3000:3000"
    volumes:
      - ./public:/app/public
    networks:
      - serverNet
    restart: always

networks:
  serverNet:
    driver: bridge