version: '3.8'
services:

  batlight:
    container_name: batlight
    image: batuatalay/batlight
    ports:
      - "3000:3000"
    volumes:
      - ./public/index.html:/app/public/index.html
    networks:
      - batlight-network
    restart: always

  nginx:
    container_name: nginx
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./public:/usr/share/nginx/html
    networks:
      - batlight-network
    restart: unless-stopped
    depends_on:
      - batlight
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost"]
      interval: 30s
      timeout: 10s
      retries: 3


# Networks
networks:
  batlight-network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.20.0.0/16