version: '3.8'
services:
  batlight:
    container_name: batlight
    image: batuatalay/batlight
    expose:
      - "3000"  # Sadece internal
    networks:
      - serverNet
    restart: always

  nginx:
    container_name: nginx
    image: nginx
    ports:
      - "80:80"
    depends_on:
      - batlight
    restart: always
    volumes:
      - ./public:/usr/share/nginx/html
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf  # Custom config
    networks:
      - serverNet

networks:
  serverNet:
    driver: bridge